"""init

Revision ID: 096ad6a71ba7
Revises: 
Create Date: 2025-09-12 17:31:37.405702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '096ad6a71ba7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('channel_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('channel_id'),
    sa.UniqueConstraint('channel_id')
    )
    op.create_table('nft',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('stars_count', sa.Integer(), nullable=True),
    sa.Column('free_throws', sa.Integer(), nullable=True),
    sa.Column('last_free_throw_date', sa.Date(), nullable=True),
    sa.Column('channel_ids_to_subscribe', sa.String(length=255), nullable=True),
    sa.Column('games_count', sa.Integer(), nullable=True),
    sa.Column('referer_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('nft')
    op.drop_table('channel')
    # ### end Alembic commands ###
